name: uwlinca-ucvm-ci

on:
  push:
    branches: [ main ]

job:
  uwlinca-build-ucvm-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/uwlinca/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/uwlinca/target" >> $GITHUB_ENV
### build ucvm(main) first 
    - name: get-ucvm 
      uses: actions/checkout@v2
      with: 
        repository: 'SCECcode/UCVM'
        ref: testMei
        path: ucvm
    - name: build-ucvm
      uses: ./ucvm/.github/actions/build-ucvm-action
      with:
         initiating-repo: 'uwlinca'
         target-model: 'uwlinca'
         target-branch: 'testMei'
   - name: Start SSH via Ngrok
     if: ${{ success() }}
     uses: luchihoratiu/debug-via-ssh@main
     with:
           NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
           NGROK_TIMEOUT: 3000
           SSH_PASS: ${{ secrets.NGROK_SECRET }}
    - name: get-result
      run: more ${{ steps.build-ucvm.outputs.build-log }}
      shell: bash
    - name: move stock uwlinca away
      run: (rm -rf $RUNNER_WORKSPACE/uwlinca/ucvm/work/model/uwlinca)
      shell: bash
### build uwlinca from github 
    - name: checkout uwlinca main
      uses: actions/checkout@v2
      with: 
        path: uwlinca
    - name: move it to the right location
      run: (mv uwlinca $RUNNER_WORKSPACE/uwlinca/ucvm/work/model; pwd; ls)
      shell: bash
    - name: build uwlinca as part of ucvm 
      run: (cd $RUNNER_WORKSPACE/uwlinca/ucvm/work/model/uwlinca; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/uwlinca-build.sh)
      shell: bash
### check ucvm is still valid
    - name: check on ucvm
      run: (source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ucvm_query -H)
      shell: bash
    - name: test uwlinca with ucvm
      run: (cd $RUNNER_WORKSPACE/uwlinca/ucvm/work/model/uwlinca; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/uwlinca-test-ucvm.sh)
      shell: bash
#    - name: Start SSH via Ngrok
#      if: ${{ success() }}
#      uses: luchihoratiu/debug-via-ssh@main
#      with:
#            NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
#            NGROK_TIMEOUT: 3000
#            SSH_PASS: ${{ secrets.NGROK_SECRET }}
    - name: test uwlinca under ucvm
      run: (cd $RUNNER_WORKSPACE/uwlinca/ucvm; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/ucvm-test.sh)
      shell: bash



